---
x-docker-logging: &docker-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"  # 로그 파일의 최대 크기 (10MB)
      max-file: "20"  # 유지할 로그 파일 개수 (최대 10개)

services:
  hive-metastore:
    <<: *docker-logging
    build: hive/dockerfile.d
    environment:
      DB_DRIVER: mysql
      SERVICE_NAME: metastore
      SERVICE_OPTS: >-
        -Djavax.jdo.option.ConnectionDriverName=com.mysql.cj.jdbc.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:mysql://mysql:3306/metastore
        -Djavax.jdo.option.ConnectionUserName=root
        -Djavax.jdo.option.ConnectionPassword=example
      IS_RESUME: "false"
    platform: linux/amd64
    ports:
      - 9083:9083
    depends_on:
      - mysql
      - minio

  spark-master:
    <<: *docker-logging
    container_name: spark-master
    build: spark/dockerfile.d
    volumes:
      - ./spark_logs:/opt/spark/logs
      - ./spark_events:/opt/spark/events
    entrypoint: ["bash", "-c"]
    platform: linux/amd64
    user: "0"
    command:
      - |
        /opt/spark/sbin/start-master.sh && \
        /opt/spark/sbin/start-thriftserver.sh \
        --master spark://spark-master:7077 && \
        /opt/spark/sbin/start-history-server.sh && \
        /opt/spark/sbin/start-worker.sh spark://spark-master:7077 && \
        tail -f a /opt/spark/logs/*.out
    ports:
      - 4040:4040
      - 7077-7082:7077-7082
      - 8080-8081:8080-8081
      - 10000:10000
      - 18080:18080
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin1234
      - AWS_REGION=us-east-1
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_PORT=7080
      - SPARK_WORKER_OPTS="-Dspark.worker.cleanup.enabled=true"
    depends_on:
      - hive-metastore
      - minio

  minio:
    container_name: minio
    build: minio/dockerfile.d
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      retries: 5
      start_period: 5s
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234

  mysql:
    image: mysql:${MYSQL_VERSION:-8.0.41}
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: metastore
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
